version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/mysql:/var/lib/mysql
      - ./docker/mysql/mysqlvolume:/mysqlvolume
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Asia/Tokyo
  php:
    build:
      context: ./docker/php
    volumes:
      - ./html:/var/www/html
    ports:
      - 10080:80
    links:
      - mysql:mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 10081:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    links:
      - mysql:mysql
